[package]
name = "tui"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
ratatui = "0.29"
crossterm = "0.29"
anyhow = "1"
unicode-segmentation = "1.12"
textwrap = "0.16"
unicode-width = "0.2"
directories = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
